# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Auto update
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Message'     
        required: false
  schedule:
  - cron:  '0 15 * * *' # Everyday at 3.00 pm US Pacific Standard Time (PST). 
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install dependencies 
      run: cd scripts; npm install
      
    - name: USA
      run: |
        cd scripts
        node usa.js 
        
    - name: "Commit downloaded files" 
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional but recommended
        # Defaults to "Apply automatic changes"
        commit_message: Daily update dataset {github.event.inputs.logLevel}

        # Optional branch name where commit should be pushed to
        # Defaults to the current branch
        #branch: feature-123

        # Optional options appended to `git-commit`
        # See https://git-scm.com/docs/git-commit for a list of available options
        #commit_options: '--no-verify --signoff'
        
        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        #file_pattern: raw/*

        # Optional local file path to the repository
        # Defaults to the root of the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: VaccineBot # defaults to "GitHub Actions"
        commit_user_email: no-reply@merlos.org # defaults to "actions@github.com"
        commit_author: Vaccine Bot <no-reply@merlos.org> # defaults to author of the commit that triggered the run

        # Optional tag message 
        # Action will create and push a new tag to the remote repository and the defined branch
        #tagging_message: 'v1.0.0'

        # Optional options appended to `git-push`
        # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
        #push_options: '--force'
    
        # Optional: Disable dirty check and always try to create a commit and push
        #skip_dirty_check: true    
    
        # Optional: Skip internal call to `git fetch`
        #skip_fetch: true
